### ISSUE TITLE
Support url missing target blank property

### ISSUE THREAD

**Issue by SirRawlins** [sorry-app/theme-whitelabel#81]
Pulling this issue from @tvb across from the status-bar project as it probably belongs here.

> This has nothing to do with the status-bar really but I wanted to post this anyway:
> 
> I have the following code on my maintenance page, however the support link does not have a target="_blank" property so my browser is blocking it for not allowing it to load insecure content. (I know it should be behind https but the service does not provide this option yet)
> 
> Could you guys add a target blank to these links? Thanks!

**Comment by tvb** [comment]
Yes I am sure it's the browser, whenever I click:

<img width="357" alt="screen shot 2018-06-04 at 10 26 11" src="https://user-images.githubusercontent.com/1263414/40906653-beecb624-67e1-11e8-828f-f21bed2f19bc.png">

I have hosted the HTML page on S3 with our own CloudFront.

**Comment by SirRawlins** [comment]
@tvb sure thing. Do you have a link that I'm able to use to access your maintenance page? It might help with debugging.

Is the uploaded file you're using the one downloaded from us? with the iFrame in it? It would be worth checking that the iFrame is linking to the https version of the maintenance page.

**Comment by tvb** [comment]
Hi,

I will email you the link. Yes we use the downloaded file.

**Comment by SirRawlins** [comment]
@tvb thanks so much for the email. The link looks good to me, the content is secure and my browsers aren't showing any warnings.

Have you made any changes since we last spoke? Are you still receiving the warning?

**Comment by tvb** [comment]
Hi @SirRawlins could you click on the support link which is http only at the bottom, thats when the browser starts complaining.

**Comment by SirRawlins** [comment]
@tvb got it! I can see exactly what you mean now. I'll take a look at this, there might be a better way to tackle this than `target="_blank"`... leave it with me. 😄

**Comment by SirRawlins** [comment]
**The problem**

o.k so the problem we have is that the downloadable maintenance page or those generated by services like CloudFlare and Heroku display the `/maintenance.html` inside an iFrame. 

Clicking the support links as you've seen tries to navigate the iFrame away, resulting in an SSL error if the iFrames parent is running over SSL, and the help centre isn't.

**Potential, but incomplete fix**

Whilst using `target="_blank"` would work, it's generally considered a little bit awkward because it breaks the 'back' and 'history' functionality in the browser etc. https://css-tricks.com/use-target_blank/

**Recommended fix**

I think the better option would be to use `target="_top"` which instead of popping open a new tab, navigates the current, top level window to the new address, preserving the 'back' button and 'history' etc.

I've given this a test on the example you've provided and it looks to work well.

What are your thoughts @tvb? Does that make sense?

**Comment by tvb** [comment]
Hm. But if `target="_blank"` just opens up a new tab why would I lose my back and history in the other tab? @SirRawlins

**Comment by SirRawlins** [comment]
@tvb it doesn't actually lose history in the new tab, it just breaks the history into two parts, before and after the new tab was created. Generally speaking, launching a new tab should only happen if you 'really' need to, in our case _top would fix the issue and it would behave as expected.

And the user would still have the option to right-click and 'open in new tab' if they wanted too.

Does that make sense?

**Comment by tvb** [comment]
Yes, I'm ok with this.

**Comment by SirRawlins** [comment]
@tvb I've just rolled out a patch for this, I've given it a quick test on the example link you sent through and it looks to be working nicely! 😄 

Let me know what you think.

**Comment by tvb** [comment]
😘 awesome!
